"""Tunable game constants."""

from __future__ import annotations

# Display
WINDOW_TITLE = "Veil"
DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 768
TARGET_FPS = 60

# Arena (fraction of window, centered)
ARENA_MARGIN = 0
ARENA_COLOR = (12, 12, 18)
WALL_COLOR = (60, 60, 80)

# Physics
DRAG = 0.98
MAX_SPEED = 420.0
ANGULAR_DRAG = 0.92

# Combat
PROJECTILE_SPEED = 520.0
PROJECTILE_SPEED_BALANCED = 700.0
PROJECTILE_LIFETIME = 1.4
PROJECTILE_DAMAGE = 15
# Hit-time range falloff: travel distance / ref_range -> multiplier lerp(close, far).
PROJECTILE_RANGE_DAMAGE_REF = PROJECTILE_SPEED * PROJECTILE_LIFETIME
RANGE_DAMAGE_LIGHT = (1.32, 0.72)
RANGE_DAMAGE_BALANCED_PEAK = 1.10
RANGE_DAMAGE_BALANCED_EDGE = 0.92
RANGE_DAMAGE_HEAVY = (0.82, 1.20)
FIRE_COOLDOWN = 0.22

# AI weapon-range bands (aligned with hit-time damage curves)
AI_IDEAL_RANGE_LIGHT = 95.0
AI_IDEAL_RANGE_BALANCED = PROJECTILE_RANGE_DAMAGE_REF * 0.5
AI_IDEAL_RANGE_HEAVY = 455.0
AI_RANGE_INNER_TOLERANCE = 70.0
AI_RANGE_OUTER_TOLERANCE = 110.0
SPREAD_COOLDOWN = 0.35
SPREAD_COUNT = 3
SPREAD_ANGLE = 0.18
CHARGED_DAMAGE = 35

# Ramming (variant multipliers applied in ship.py)
RAM_BASE_DAMAGE = 25.0
MIN_RAM_IMPACT = 40.0
SHIP_RAM_RESTITUTION = 0.55
SPAWN_INVULN_SECONDS = 3.0
SPAWN_MIN_DISTANCE = 140.0

# Waves
WAVE_BREAK_SECONDS = 2.5
WAVE_ENEMY_BASE = 3
WAVE_ENEMY_PER_WAVE = 1
WAVE_ENEMY_JITTER = 1
WAVE_ENEMY_MAX = 10
ASTEROID_MIN_COUNT = 2
ASTEROID_MAX_COUNT = 4
ASTEROID_SPAWN_CHANCE = 0.85
ASTEROID_SPAWN_MIN_INTERVAL = 2.0
ASTEROID_SPAWN_MAX_INTERVAL = 6.0
ASTEROID_DRIFT_MIN = 12.0
ASTEROID_DRIFT_MAX = 28.0

# Power-ups
POWERUP_SPAWN_CHANCE = 0.82
POWERUP_LIFETIME = 18.0
POWERUP_SPAWN_INTERVAL = 7.0
POWERUP_AI_SPAWN_INTERVAL = 4.0
POWERUP_MAX_ON_FIELD = 3
POWERUP_DEATH_DROP_CHANCE = 0.5
POWERUP_BOUT_START_COUNT = 2
SHIELD_DURATION = 10.0
FIRE_RATE_DURATION = 8.0
SPREAD_WEAPON_DURATION = 12.0
FIRE_RATE_COOLDOWN_MULT = 0.38

# AI Arena
AI_ARENA_SHIP_COUNT = 6
AI_ARENA_RESTART_DELAY = 4.0
CHAMPION_MAX_STACKS = 5
CHAMPION_BOSS_WINS = 5
# Per-stack champion bonuses: stronger early (reach 5), softer 4–5 (same totals).
CHAMPION_HEALTH_BY_STACK = [0.18, 0.145, 0.12, 0.07, 0.035]
CHAMPION_THRUST_BY_STACK = [0.13, 0.10, 0.085, 0.055, 0.03]
CHAMPION_FIRE_BY_STACK = [0.145, 0.115, 0.095, 0.06, 0.035]
CHAMPION_BOUT_SHIELD_WINS = 1
CHAMPION_BOUT_INVULN = 1.6
CHAMPION_BOUT_INVULN_PER_WIN = 0.4
BOSS_HEALTH_MULT = 1.06
BOSS_THRUST_MULT = 1.04
BOSS_FIRE_MULT = 0.96
BOSS_HULL_SCALE = 1.18
BOSS_PULSE_RADIUS = 95.0
BOSS_PULSE_DAMAGE = 16.0
BOSS_PULSE_COOLDOWN = 5.5
BOSS_PULSE_FLASH = 0.35

# AI orbit-break: enter early, shoot loose, force a shot if still circling
ORBIT_BREAK_CHASE_TIMER = 0.40
ORBIT_BREAK_LEAD_TIMER = 0.50
ORBIT_BREAK_MUTUAL_TIMER = 0.22
ORBIT_BREAK_MAX_DURATION = 0.70
ORBIT_BREAK_FORCE_SHOT_TIMER = 0.18
ORBIT_BREAK_FORCE_SHOT_WINDOW = 0.32
ORBIT_BREAK_FIRE_BEARING = 1.18
ORBIT_BREAK_FORCE_FIRE_RANGE = 500.0
ORBIT_BREAK_AIM_GATE = 0.05

# AI injury / pickup
AI_INJURY_HEALTH_RATIO = 0.45
AI_INJURY_BRAKE_SPEED = 200.0
AI_INJURY_MAX_SPEED = 300.0
AI_POWERUP_SEEK_SCORE = 0.38
AI_POWERUP_EASY_REACH_DIST = 140.0
AI_POWERUP_EASY_REACH_SCORE = 0.28
# Keep AI fights in the visible center — soft bias, not hard walls
AI_ARENA_EDGE_MARGIN_FRAC = 0.24
AI_ARENA_CENTER_BIAS_MAX = 0.40
AI_ARENA_WRAP_CHASE_EDGE = 0.22
ARENA_SPAWN_INSET_FRAC = 0.18

AI_POWERUP_ABORT_RISK = 0.52
AI_POWERUP_CAUTION_RISK = 0.30
AI_POWERUP_RISK_PENALTY = 0.55

# Target pick: prefer lined-up / wounded foes over raw nearest distance
AI_TARGET_SWITCH_MARGIN = 0.12
AI_TARGET_MAX_DIST = 780.0

# 1v1 discipline: hold range and shoot instead of full-throttle fly-bys
AI_ENGAGE_QUALITY_THRESHOLD = 0.58
AI_ENGAGE_HOLD_THRUST = 0.30
AI_ENGAGE_SNAP_THRUST = 0.18
AI_SOLO_DOGFIGHT_MAX_DIST = 500.0

# Heavy 1v1: slow hulls need deliberate closes, not endless long-range meanders
AI_HEAVY_DUEL_COMMIT_AFTER = 1.4
AI_HEAVY_DUEL_COMMIT_DURATION = 1.5
AI_HEAVY_DUEL_COMMIT_THRUST = 0.85
AI_HEAVY_DUEL_CLOSE_THRUST = 0.68
AI_HEAVY_DUEL_BAND_THRUST = 0.55
AI_HEAVY_DUEL_CENTER_BIAS = 0.3

# Enemy motion prediction (acceleration + turn continuation for aim/steer)
AI_PREDICT_ACCEL_BLEND = 0.34
AI_PREDICT_MAX_ACCEL = 260.0
AI_PREDICT_TURN_BLEND_MAX = 0.62
AI_PREDICT_TURN_SENSITIVITY = 0.42
AI_PREDICT_HEAVY_TURN_MULT = 1.28
AI_PREDICT_AIM_HORIZON_MAX = 0.38

# Scoring
SCORE_PER_KILL = 100
SCORE_PER_SECOND = 2
SCORE_PER_WAVE = 250

HIGH_SCORE_FILE = "highscores.json"
BINDINGS_FILE = "bindings.json"
SETTINGS_FILE = "settings.json"

# Audio — drop generated MP3s into MUSIC_DIR (e.g. from a separate music project)
MUSIC_DIR = "assets/music"
DEFAULT_SFX_VOLUME = 0.8
DEFAULT_MUSIC_VOLUME = 0.6
VOLUME_STEP = 0.05
MUSIC_FADE_OUT_SECONDS = 3.0
MUSIC_GAP_SECONDS = 1.0
MUSIC_CHANNEL = 7

# Behind-target gun run: snap nose toward target instead of kiting sideways
AI_SHOT_ALIGN_BEARING = 0.32